### ISSUE TITLE
Image/Thumbnail is getting beyond container bounds

### ISSUE THREAD

**Issue by isaniomoraes** [lmcjt37/curated-tv-and-film#37]
Preview:
![screenshot from 2018-10-23 00-29-29](https://user-images.githubusercontent.com/3224086/47333872-fa53d980-d65a-11e8-925b-d8704ebd7f58.png)

I'd recommend remove the fixed height (`height: 200px`) on **.item-thumbnail img {}** selector and set:
```css
.item-thumbnail img {
  max-width: 100%;
  height: auto;
}
```
